### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by akien-mga** [sketchfab/godot-plugin#9]
Hi there,

Thanks a lot for this great plugin, works quite fine in Godot's *master* branch :)

This repo lacks licensing information, it would be nice to add a `LICENSE` file that specifies the license and copyright. On the Godot [Asset Library](https://godotengine.org/asset-library/asset/182) it's listed as MIT, but this is not correlated here as far as I can see.

**Comment by AurL** [comment]
Hi @akien-mga , 

I just pushed a LICENSE (MIT) file to the repo as it has been omitted.
Thanks
